# IBM Cloud Code Engine Deployment Configuration for Agentic City Planner
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-auth
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-auth
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: "cityplanner_secret_key"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-planner
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-planner
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: IBM_WATSONX_API_KEY
          value: "<your-watsonx-api-key>"
        - name: IBM_WATSONX_URL
          value: "https://us-south.ml.cloud.ibm.com"
        - name: IBM_WATSONX_PROJECT_ID
          value: "<your-watsonx-project-id>"
        - name: MODEL_NAME
          value: "ibm/granite-3-2-8b-instruct"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-simulation
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-simulation
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-document
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-document
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        - name: WATSONX_APIKEY
          value: "<your-watsonx-api-key>"
        - name: WATSONX_URL
          value: "https://us-south.ml.cloud.ibm.com"
        - name: WATSONX_PROJECT_ID
          value: "<your-watsonx-project-id>"
        - name: EMBEDDING_MODEL_ID
          value: "ibm/slate-125m-english-rtrvr"
        - name: CHROMA_PERSIST_DIR
          value: "/app/chroma_db"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-parser
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-parser
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          value: "8003"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cityplanner-api
spec:
  template:
    spec:
      containers:
      - image: us.icr.io/<your-namespace>/cityplanner-api
        ports:
        - containerPort: 8080
        env:
        - name: API_GATEWAY_PORT
          value: "8080"
        - name: AUTH_URL
          value: "http://cityplanner-auth.<region>.codeengine.appdomain.cloud"
        - name: PLANNER_URL
          value: "http://cityplanner-planner.<region>.codeengine.appdomain.cloud"
        - name: SIMULATION_URL
          value: "http://cityplanner-simulation.<region>.codeengine.appdomain.cloud"
        - name: DOCUMENT_URL
          value: "http://cityplanner-document.<region>.codeengine.appdomain.cloud"
        - name: PARSER_URL
          value: "http://cityplanner-parser.<region>.codeengine.appdomain.cloud"